before_install:
  - sudo apt-get install -y swig
language: java
before_script:
  - curl -L -o zenohd https://github.com/atolab/atobin/raw/master/zenoh/unstable/ubuntu/16.04/zenohd
  - chmod +x zenohd
  - ./zenohd --verbosity=debug > ./zenohd.out 2>&1 &
after_script:
  - killall zenohd
after_failure:
  - cat ./zenohd.out