#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#

before_install:
  - sudo apt-get install -y libev4
  - sudo apt-get install -y swig
language: java
jdk: openjdk8
before_script:
  - curl -L -o zenohd https://github.com/atolab/atobin/raw/master/zenoh/unstable/ubuntu/16.04/zenohd
  - chmod +x zenohd
  - ./zenohd --verbosity=info > ./zenohd.out 2>&1 &
script: mvn verify -Pit -Pcodecov
after_script:
  - killall zenohd
after_failure:
  - cat ./zenohd.out
after_success:
  - bash <(curl -s https://codecov.io/bash)